name: "tagged-release"
on:
  push:
    tags:
      - "v*"
jobs:
  publishGitRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          draft: false
          prerelease: false